# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-secrets-kv
  namespace: api-ns
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: abf935ab-8b09-4e3f-83d1-57b2ff7742df   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: openhack-team03-keyvault        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_USER
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret
          objectAlias: SQL_SERVER
        - |
          objectName: SQL-DBNAME
          objectType: secret
          objectAlias: SQL_DBNAME
    tenantId: b874a4ff-8181-4e38-8f0d-bfbdcb91b50b                 # The tenant ID of the key vault