# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file, it will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  SQL_USER: c3FsYWRtaW5oSXM2ODY5
  SQL_PASSWORD: Z2VuWjAwI2Q=
  SQL_SERVER: c3Fsc2VydmVyaGlzNjg2OS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: bXlkcml2aW5nREI=
kind: Secret
metadata:
  name: sql-credentials
  namespace: default
type: Opaque